### ISSUE TITLE
Pzem-004t v3 + Esp32 DEVKITV1

### ISSUE THREAD

**Issue by M4carloz** [mandulaj/PZEM-004T-v30#105]
Olá pessoal, estou tendo problemas para utilizar um sensor pzem-004t 100A V3 com o Esp32 DEVKIT1.

A montagem foi feita da seguinte forma: As portas Vp e GND do Esp32 estão ligadas em série com as portas 5V E GND do sensor em uma protoboard. As portas RX e TX do sensor estão conectadas as portas TX2 e RX2 do ESP32, respectivamente, Ambas passando por um divisor de tensão, de 5V para 3,3V.
  Quanto ao código,  já testei os códigos presentes nesta e em outras bibliotecas, de alguns sites e vídeos que vi, até mesmo me arrisquei a programar alguma coisa, mas não obtive êxito em minhas tentativas. A led RX do sensor acende sempre que aperto o botão EN do Esp32, indicando q existe alguma forma de comunicação entre os dois. E logo em seguida, a led RX brilha rapidamente, indicando que existe um retorno do sensor para o esp. Entretanto, as respostas nunca vem como esperado, seja não enviando os dados de leitura de determinada carga ou nas tentativas de mudar o endereço do sensor, onde sempre aparece a mensagem "Error setting address".
 Vi em outros fóruns que esse problema já ocorreu com outras pessoas, mas não vi nenhuma resposta que tenha resolvido meu problema ainda.   

![IMG_20230227_163523394.jpg](https://user-images.githubusercontent.com/126199348/221665121-804ae6b9-77d2-475a-bc7f-dda1faf6cf5c.jpg)

![IMG_20230227_163539893.jpg](https://user-images.githubusercontent.com/126199348/221665136-8b4d2787-1774-4869-8419-47c0157fe43d.jpg)

![IMG_20230227_163544481.jpg](https://user-images.githubusercontent.com/126199348/221665161-05033c58-163b-4ba0-b170-472a2fbe6433.jpg)

![IMG_20230227_153841646.jpg](https://user-images.githubusercontent.com/126199348/221665178-cdf5c2e5-026e-4bd2-a4dc-f9513316c9ef.jpg)

**Comment by mandulaj** [comment]
Hi @M4carloz, I will reply in English. What happens if you power the PZEM with 3.3V and connect the RX/TX lines directly from the ESP32. (Without using any voltage divider).

You see, the 5V power only powers the opto-coupler, not the actual PZEM chip. Also please try swapping the RX/TX lines, just in case you have them the wrong way around. 

I am not sure which sketch you are using, but if you use this sketch [PZEMHardSerial](https://github.com/mandulaj/PZEM-004T-v30/blob/master/examples/PZEMHardSerial/PZEMHardSerial.cpp) it will communicate using the default (broadcast) address, so you shouldn't be getting any Errors setting an address.

**Comment by M4carloz** [comment]
Muito obrigado irmão, funcionou perfeitamente.

![IMG_20230228_150254701](https://user-images.githubusercontent.com/126199348/221941084-213fc017-21cb-467b-b4fb-52521a3e0133.jpg)

![1](https://user-images.githubusercontent.com/126199348/221941152-d7f0bb4b-5f72-43b8-bb06-f693c73b0def.png)
