### ISSUE TITLE
is there possible to change the CT (Current Transformer)?

### ISSUE THREAD

**Issue by Meisam-kh** [mandulaj/PZEM-004T-v30#118]
I need to measure the current passing through the copper busbar. But its dimensions are larger than the diameter of the current transformer.

Is there a solution to replace the current trans with a larger diameter one?

**Comment by mandulaj** [comment]
I see no reason why this should be an issue. Just a couple of points.

1. If I remember correctly, the CT that comes with the PZEM is a 10Ohm 100A 1000/1 transformer. Your new transformer should have similar specifications in order to work well.
2. You are unlikely to get exactly equivalent CT, thus your current values are going to be skewed. Luckily, the values should be linearly proportional. You must calibrate the sensor with a known Current measurement probe to find the coefficient. Then it will be just a question of multiplying the current, power and energy by this coefficient. 

Hope this helps.
